language: go
install:
- "./scripts/install_splitsh-lite"
- git fetch --unshallow
script: PATH=${PATH}:./bin ./scripts/push_manyrepos
before_install:
- openssl aes-256-cbc -K $encrypted_7fee10189ef4_key -iv $encrypted_7fee10189ef4_iv
  -in cucumber_manyrepo_id_rsa.enc -out cucumber_manyrepo_id_rsa -d
- eval `ssh-agent -s`
- ssh-add cucumber_manyrepo_id_rsa
env:
  global:
  - ENCRYPTION_LABEL: "7fee10189ef4"
  - COMMIT_AUTHOR_EMAIL: "cucumber-manyrepo@cucumber.io"
