version: 2

jobs:
  test-default:
    working_directory: ~/app
    docker:
      - image: cucumber/cucumber-build:39e69ae56ad2861d86a8f26d3cec0285
    steps:
      - checkout
      - run: make --directory ./cucumber-expressions/java
      - run: make --directory ./cucumber-expressions/javascript
      - run: make --directory ./cucumber-expressions/ruby
      - run: make --directory ./event-protocol
      - run: make --directory ./gherkin/c
      - run: make --directory ./gherkin/javascript
      - run: make --directory ./gherkin/go
      - run: make --directory ./gherkin/java
      - run: make --directory ./gherkin/objective-c
      - run: make --directory ./gherkin/perl
      - run: make --directory ./gherkin/python
      - run: make --directory ./gherkin/ruby
      - run: make --directory ./tag-expressions/java
      - run: make --directory ./tag-expressions/javascript
      - run: make --directory ./tag-expressions/ruby
      # cucumber-redux depends on event-protocol and gherkin/javascript
      - run: make --directory ./cucumber-redux
      # cucumber-redux depends on cucumber-redux, event-protocol and gherkin/javascript
      - run: make --directory ./cucumber-react

  test-dotnet:
    working_directory: ~/app
    docker:
      - image: cucumber/cucumber-build-dotnet:30a8674a75afb13b4d2eb81e551ecb74
    steps:
      - checkout
      - run: make --directory ./gherkin/dotnet

workflows:
  version: 2
  test:
    jobs:
      - test-default
      - test-dotnet
